media:
  - type: "General News"
    type_slug: "general"
    sources:
      - name: "BBC News"
        url: "https://www.bbc.com"
        short_url: "www.bbc.com"
      - name: "Reuters"
        url: "https://www.reuters.com"
        short_url: "www.reuters.com"
      - name: "Associated Press (AP)"
        url: "https://apnews.com"
        short_url: "apnews.com"
      - name: "The Guardian"
        url: "https://www.theguardian.com"
        short_url: "www.theguardian.com"
      - name: "Al Jazeera"
        url: "https://www.aljazeera.com"
        short_url: "www.aljazeera.com"
      - name: "France 24"
        url: "https://www.france24.com"
        short_url: "www.france24.com"
      - name: "Deutsche Welle (DW)"
        url: "https://www.dw.com"
        short_url: "www.dw.com"
      - name: "The New York Times"
        url: "https://www.nytimes.com"
        short_url: "www.nytimes.com"
      - name: "Washington Post"
        url: "https://www.washingtonpost.com"
        short_url: "www.washingtonpost.com"

  - type: "Geopolitics & Defense"
    type_slug: "geopolitics"
    sources:
      - name: "Janes"
        url: "https://www.janes.com"
        short_url: "www.janes.com"
      - name: "War on the Rocks"
        url: "https://warontherocks.com"
        short_url: "warontherocks.com"
      - name: "The Diplomat"
        url: "https://thediplomat.com"
        short_url: "thediplomat.com"
      - name: "Defense News"
        url: "https://www.defensenews.com"
        short_url: "www.defensenews.com"
      - name: "Breaking Defense"
        url: "https://breakingdefense.com"
        short_url: "breakingdefense.com"
      - name: "Foreign Policy"
        url: "https://foreignpolicy.com"
        short_url: "foreignpolicy.com"
      - name: "Geopolitical Futures"
        url: "https://geopoliticalfutures.com"
        short_url: "geopoliticalfutures.com"
      - name: "Military Times"
        url: "https://www.militarytimes.com"
        short_url: "www.militarytimes.com"
      - name: "Conflict Intelligence Team (CIT)"
        url: "https://cit.team/en"
        short_url: "cit.team/en"

  - type: "OSINT & Investigative Journalism"
    type_slug: "investigation"
    sources:
      - name: "Bellingcat"
        url: "https://www.bellingcat.com"
        short_url: "www.bellingcat.com"
      - name: "Oryx"
        url: "https://www.oryxspioenkop.com"
        short_url: "www.oryxspioenkop.com"
      - name: "Investigative Dashboard"
        url: "https://www.investigativedashboard.org"
        short_url: "www.investigativedashboard.org"
      - name: "ProPublica"
        url: "https://www.propublica.org"
        short_url: "www.propublica.org"
      - name: "The Intercept"
        url: "https://www.theintercept.com"
        short_url: "www.theintercept.com"
      - name: "All Eyes on Wagner"
        url: "https://wagner-pmc.com"
        short_url: "wagner-pmc.com"
      - name: "Grey Dynamics"
        url: "https://greydynamics.com"
        short_url: "greydynamics.com"
      - name: "Intel Techniques Blog (Michael Bazzell)"
        url: "https://inteltechniques.com/blog.html"
        short_url: "inteltechniques.com"
      - name: "SecLists"
        url: "https://seclists.org"
        short_url: "seclists.org"
      - name: "OpenSanctions"
        url: "https://www.opensanctions.org"
        short_url: "opensanctions.org"
      - name: "Centre for Analysis of Strategies and Technologies (CAST)"
        url: "https://cast.ru"
        short_url: "cast.ru"

  - type: "Conflict Monitoring"
    type_slug: "conflict"
    sources:
      - name: "Liveuamap"
        url: "https://liveuamap.com"
        short_url: "liveuamap.com"
      - name: "Global Incident Map"
        url: "https://www.globalincidentmap.com"
        short_url: "www.globalincidentmap.com"
      - name: "Crisis Group"
        url: "https://www.crisisgroup.org"
        short_url: "www.crisisgroup.org"
      - name: "ACLED (Armed Conflict Location & Event Data)"
        url: "https://acleddata.com"
        short_url: "acleddata.com"
      - name: "SouthFront"
        url: "https://southfront.org"
        short_url: "southfront.org"
      - name: "Crisis24"
        url: "https://crisis24.garda.com"
        short_url: "crisis24.garda.com"
      - name: "MapHub"
        url: "https://maphub.net"
        short_url: "maphub.net"
      - name: "Syrian Civil War Map"
        url: "https://syriancivilwarmap.com"
        short_url: "syriancivilwarmap.com"
      - name: "Tracking Terrorism"
        url: "https://trackingterrorism.org"
        short_url: "trackingterrorism.org"

  - type: "Economic & Business News"
    type_slug: "economy"
    sources:
      - name: "Bloomberg"
        url: "https://www.bloomberg.com"
        short_url: "www.bloomberg.com"
      - name: "Yahoo Finance"
        url: "https://finance.yahoo.com"
        short_url: "finance.yahoo.com"
      - name: "Financial Times (FT)"
        url: "https://www.ft.com"
        short_url: "www.ft.com"
      - name: "Economist"
        url: "https://www.economist.com"
        short_url: "www.economist.com"
      - name: "MarketWatch"
        url: "https://www.marketwatch.com"
        short_url: "www.marketwatch.com"
      - name: "Reuters Markets"
        url: "https://www.reuters.com/markets"
        short_url: "www.reuters.com/markets"
      - name: "Forbes"
        url: "https://www.forbes.com"
        short_url: "www.forbes.com"
      - name: "Morningstar"
        url: "https://www.morningstar.com"
        short_url: "www.morningstar.com"

  - type: "News Aggregators"
    type_slug: "aggregator"
    sources:
      - name: "Google News"
        url: "https://news.google.com"
        short_url: "news.google.com"
      - name: "Bing News"
        url: "https://www.bing.com/news"
        short_url: "www.bing.com/news"
      - name: "Yahoo News"
        url: "https://news.yahoo.com"
        short_url: "news.yahoo.com"
      - name: "Feedly"
        url: "https://feedly.com"
        short_url: "feedly.com"

  - type: "Region-Specific Sources"
    type_slug: "region"
    regions:
      - region: "Russia"
        sources:
          - name: "TASS"
            url: "https://www.tass.com"
            short_url: "www.tass.com"
          - name: "RT (Russia Today)"
            url: "https://www.rt.com"
            short_url: "www.rt.com"
          - name: "Kommersant"
            url: "https://www.kommersant.ru"
            short_url: "www.kommersant.ru"
      - region: "China"
        sources:
          - name: "China Daily"
            url: "https://www.chinadaily.com.cn"
            short_url: "www.chinadaily.com.cn"
          - name: "Global Times"
            url: "https://www.globaltimes.cn"
            short_url: "www.globaltimes.cn"
      - region: "Middle East"
        sources:
          - name: "Middle East Eye"
            url: "https://www.middleeasteye.net"
            short_url: "www.middleeasteye.net"
          - name: "Al Monitor"
            url: "https://www.al-monitor.com"
            short_url: "www.al-monitor.com"
      - region: "Europe"
        sources:
          - name: "Le Monde"
            url: "https://www.lemonde.fr"
            short_url: "www.lemonde.fr"
          - name: "Der Spiegel"
            url: "https://www.spiegel.de/international"
            short_url: "www.spiegel.de/international"

  - type: "Cybersecurity & Tech News"
    type_slug: "cybersecurity"
    sources:
      - name: "Krebs on Security"
        url: "https://krebsonsecurity.com"
        short_url: "krebsonsecurity.com"
      - name: "The Hacker News"
        url: "https://thehackernews.com"
        short_url: "thehackernews.com"
      - name: "SecurityWeek"
        url: "https://www.securityweek.com"
        short_url: "www.securityweek.com"
      - name: "BleepingComputer"
        url: "https://www.bleepingcomputer.com"
        short_url: "www.bleepingcomputer.com"
      - name: "Threatpost"
        url: "https://threatpost.com"
        short_url: "threatpost.com"
      - name: "Dark Reading"
        url: "https://www.darkreading.com"
        short_url: "www.darkreading.com"
      - name: "ZDNet Security"
        url: "https://www.zdnet.com/enterprise/security"
        short_url: "www.zdnet.com"
      - name: "SC Magazine"
        url: "https://www.scmagazine.com"
        short_url: "www.scmagazine.com"
      - name: "CyberScoop"
        url: "https://www.cyberscoop.com"
        short_url: "www.cyberscoop.com"
      - name: "WIRED Security"
        url: "https://www.wired.com/category/security"
        short_url: "www.wired.com"
      - name: "Ars Technica Security"
        url: "https://arstechnica.com/information-technology"
        short_url: "arstechnica.com"
      - name: "Motherboard (Vice)"
        url: "https://www.vice.com/en/topic/hacking"
        short_url: "www.vice.com"
      - name: "CSO Online"
        url: "https://www.csoonline.com"
        short_url: "www.csoonline.com"
      - name: "Help Net Security"
        url: "https://www.helpnetsecurity.com"
        short_url: "www.helpnetsecurity.com"
      - name: "HackRead"
        url: "https://www.hackread.com"
        short_url: "www.hackread.com"
      - name: "Infosecurity Magazine"
        url: "https://www.infosecurity-magazine.com"
        short_url: "www.infosecurity-magazine.com"
      - name: "Naked Security (Sophos)"
        url: "https://nakedsecurity.sophos.com"
        short_url: "nakedsecurity.sophos.com"
      - name: "Schneier on Security"
        url: "https://www.schneier.com"
        short_url: "www.schneier.com"
      - name: "Malwarebytes Labs"
        url: "https://blog.malwarebytes.com"
        short_url: "blog.malwarebytes.com"
      - name: "Exploit Database (Offensive Security)"
        url: "https://www.exploit-db.com"
        short_url: "www.exploit-db.com"
      - name: "MITRE ATT&CK"
        url: "https://attack.mitre.org"
        short_url: "attack.mitre.org"
      - name: "CISA Alerts (Cybersecurity & Infrastructure Security Agency)"
        url: "https://www.cisa.gov/news-events/alerts"
        short_url: "www.cisa.gov"
      - name: "Project Zero (Google)"
        url: "https://googleprojectzero.blogspot.com"
        short_url: "googleprojectzero.blogspot.com"
      - name: "CERT-EU"
        url: "https://cert.europa.eu"
        short_url: "cert.europa.eu"
      - name: "CERT-CC (Carnegie Mellon)"
        url: "https://www.cert.org"
        short_url: "www.cert.org"
      - name: "Bad Packets"
        url: "https://badpackets.net"
        short_url: "badpackets.net"

  - type: "Blockchain and Crypto"
    type_slug: "blockchain"
    sources:
      - name: "Elliptic"
        url: "https://www.elliptic.co"
        short_url: "www.elliptic.co"
      - name: "CipherTrace"
        url: "https://ciphertrace.com"
        short_url: "ciphertrace.com"
      - name: "Whale Alert"
        url: "https://whale-alert.io"
        short_url: "whale-alert.io"
      - name: "BTC Explorer"
        url: "https://www.blockchain.com/explorer"
        short_url: "www.blockchain.com"
      - name: "Chainalysis"
        url: "https://www.chainalysis.com"
        short_url: "www.chainalysis.com"

  - type: "Spying and Secrets"
    type_slug: "secrets"
    sources:
      - name: "SpyTalk"
        url: "https://www.spytalk.co"
        short_url: "spytalk.co"
      - name: "IntelNews.org"
        url: "https://intelnews.org"
        short_url: "intelnews.org"
      - name: "The Cipher Brief"
        url: "https://www.thecipherbrief.com"
        short_url: "www.thecipherbrief.com"
      - name: "Stratfor Worldview"
        url: "https://worldview.stratfor.com"
        short_url: "worldview.stratfor.com"