media:
  - type: "SOCMINT Developers"
    type_slug: "socmint_developers"
    sources:
      - name: "GitHub"
        url: "https://github.com"
        short_url: "github.com"
      - name: "Dribbble"
        url: "https://dribbble.com"
        short_url: "dribbble.com"
      - name: "HackerNoon"
        url: "https://hackernoon.com"
        short_url: "hackernoon.com"
      - name: "DevDocs"
        url: "https://devdocs.io"
        short_url: "devdocs.io"
      - name: "Hacker News"
        url: "https://news.ycombinator.com"
        short_url: "news.ycombinator.com"
      - name: "Diff Blog"
        url: "https://diff.blog"
        short_url: "diff.blog"
      - name: "Udemy"
        url: "https://udemy.com"
        short_url: "udemy.com"
      - name: "DigitalOcean"
        url: "https://digitalocean.com"
        short_url: "digitalocean.com"
      - name: "Indie Hackers"
        url: "https://indiehackers.com"
        short_url: "indiehackers.com"
      - name: "Resumake"
        url: "https://resumake.io"
        short_url: "resumake.io"
      - name: "LeetCode"
        url: "https://leetcode.com"
        short_url: "leetcode.com"
      - name: "Glassdoor"
        url: "https://glassdoor.com"
        short_url: "glassdoor.com"
      - name: "ProductHunt"
        url: "https://producthunt.com"
        short_url: "producthunt.com"
      - name: "Stack Overflow"
        url: "https://stackoverflow.com"
        short_url: "stackoverflow.com"
      - name: "Hack The Box"
        url: "https://hackthebox.com"
        short_url: "hackthebox.com"
      - name: "Notion"
        url: "https://notion.so"
        short_url: "notion.so"
      - name: "WordPress"
        url: "https://wordpress.com"
        short_url: "wordpress.com"

  - type: "SOCMINT Extreme"
    type_slug: "socmint_extreme"
    sources:
      - name: "BitChute"
        url: "https://bitchute.com"
        short_url: "bitchute.com"
      - name: "Rumble"
        url: "https://rumble.com"
        short_url: "rumble.com"
      - name: "Odysee"
        url: "https://odysee.com"
        short_url: "odysee.com"
      - name: "Gab"
        url: "https://gab.com"
        short_url: "gab.com"
      - name: "Gettr"
        url: "https://gettr.com"
        short_url: "gettr.com"
      - name: "Brighteon"
        url: "https://brighteon.com"
        short_url: "brighteon.com"
      - name: "UGETube"
        url: "https://ugetube.com"
        short_url: "ugetube.com"

  - type: "SOCMINT Link Sources"
    type_slug: "socmint_link_sources"
    sources:
      - name: "Linktree"
        url: "https://linktr.ee"
        short_url: "linktr.ee"
      - name: "AllMyLinks"
        url: "https://allmylinks.com"
        short_url: "allmylinks.com"
      - name: "Cash App"
        url: "https://cash.app"
        short_url: "cash.app"
      - name: "Patreon"
        url: "https://patreon.com"
        short_url: "patreon.com"
      - name: "Fiverr"
        url: "https://fiverr.com"
        short_url: "fiverr.com"
      - name: "Buy Me a Coffee"
        url: "https://buymeacoffee.com"
        short_url: "buymeacoffee.com"
      - name: "Ko-fi"
        url: "https://ko-fi.com"
        short_url: "ko-fi.com"
      - name: "Google Drive File"
        url: "https://drive.google.com/file"
        short_url: "drive.google.com/file"
      - name: "Google Drive Folder"
        url: "https://drive.google.com/folder"
        short_url: "drive.google.com/folder"
      - name: "Scribd"
        url: "https://scribd.com"
        short_url: "scribd.com"

  - type: "SOCMINT Trading"
    type_slug: "socmint_trading"
    sources:
      - name: "Wyckoff Tagging"
        url: "https://wyckofftagging.com"
        short_url: "wyckofftagging.com"
      - name: "ForumCrypto"
        url: "https://forumcrypto.fr/profile"
        short_url: "forumcrypto.fr/profile"
      - name: "Bitcoin Talk"
        url: "https://bitcointalk.org"
        short_url: "bitcointalk.org"
      - name: "CryptoFR"
        url: "https://cryptofr.com"
        short_url: "cryptofr.com"
      - name: "TradingView"
        url: "https://tradingview.com/u/"
        short_url: "tradingview.com/u/"
      - name: "Investing"
        url: "https://investing.com/members/"
        short_url: "investing.com/members/"
      - name: "Finary Community"
        url: "https://community.finary.com/u"
        short_url: "community.finary.com/u"
      - name: "Altcoin Stalks"
        url: "https://altcoinstalks.com"
        short_url: "altcoinstalks.com"
      - name: "Boursorama"
        url: "https://boursorama.com/espace-membres/profil/"
        short_url: "boursorama.com/espace-membres/profil/"
      - name: "MyFXBook"
        url: "https://myfxbook.com/members/"
        short_url: "myfxbook.com/members/"
      - name: "Forex Factory"
        url: "https://forexfactory.com/"
        short_url: "forexfactory.com"
      - name: "Stocktwits"
        url: "https://stocktwits.com/"
        short_url: "stocktwits.com"
      - name: "Investor Hub"
        url: "https://investorshub.advfn.com/user"
        short_url: "investorshub.advfn.com/user"

  - type: "SOCMINT NSFW"
    type_slug: "socmint_nsfw"
    sources:
      - name: "Pornhub"
        url: "https://pornhub.com"
        short_url: "pornhub.com"
      - name: "Pornhub Users"
        url: "https://pornhub.com/users/"
        short_url: "pornhub.com/users/"
      - name: "XVideos"
        url: "https://xvideos.com"
        short_url: "xvideos.com"
      - name: "XVideos Profiles"
        url: "https://xvideos.com/profiles"
        short_url: "xvideos.com/profiles"
      - name: "OnlyFans"
        url: "https://onlyfans.com"
        short_url: "onlyfans.com"
      - name: "MYM Fans"
        url: "https://mym.fans"
        short_url: "mym.fans"
      - name: "Fansly"
        url: "https://fansly.com"
        short_url: "fansly.com"
      - name: "Erome"
        url: "https://erome.com"
        short_url: "erome.com"
      - name: "Redgifs"
        url: "https://redgifs.com"
        short_url: "redgifs.com"
      - name: "SpankBang"
        url: "https://fr.spankbang.com"
        short_url: "fr.spankbang.com"
      - name: "SpankBang Profiles"
        url: "https://fr.spankbang.com/profile"
        short_url: "fr.spankbang.com/profile"
      - name: "FurAffinity"
        url: "https://furaffinity.net"
        short_url: "furaffinity.net"
      - name: "ApClips"
        url: "https://apclips.com"
        short_url: "apclips.com"
      - name: "AdmireMe.VIP"
        url: "https://admireme.vip"
        short_url: "admireme.vip"
      - name: "All Things Worn"
        url: "https://allthingsworn.com"
        short_url: "allthingsworn.com"
      - name: "BongaCams"
        url: "https://bongacams.com"
        short_url: "bongacams.com"
      - name: "Chaturbate"
        url: "https://chaturbate.com"
        short_url: "chaturbate.com"
      - name: "JustForFans"
        url: "https://justfor.fans"
        short_url: "justfor.fans"
      - name: "LoyalFans"
        url: "https://loyalfans.com"
        short_url: "loyalfans.com"
      - name: "DarkFans"
        url: "https://darkfans.com"
        short_url: "darkfans.com"
      - name: "LadyXena"
        url: "https://ladyxena.com"
        short_url: "ladyxena.com"
      - name: "RocketTube"
        url: "https://rockettube.com"
        short_url: "rockettube.com"
      - name: "XHamster"
        url: "https://xhamster.com"
        short_url: "xhamster.com"
      - name: "RedTube"
        url: "https://redtube.com"
        short_url: "redtube.com"
      - name: "YouPorn"
        url: "https://youporn.com"
        short_url: "youporn.com"
      - name: "Rule34 Paheal"
        url: "https://rule34.paheal.net"
        short_url: "rule34.paheal.net"
      - name: "Clips4Sale"
        url: "https://clips4sale.com"
        short_url: "clips4sale.com"

  - type: "SOCMINT Social"
    type_slug: "socmint_social"
    sources:
      - name: "Instagram"
        url: "https://instagram.com"
        short_url: "instagram.com"
      - name: "Twitter"
        url: "https://twitter.com"
        short_url: "twitter.com"
      - name: "Facebook"
        url: "https://facebook.com"
        short_url: "facebook.com"
      - name: "TikTok"
        url: "https://tiktok.com"
        short_url: "tiktok.com"
      - name: "LinkedIn"
        url: "https://linkedin.com"
        short_url: "linkedin.com"
      - name: "LinkedIn Profiles"
        url: "https://linkedin.com/in"
        short_url: "linkedin.com/in"
      - name: "Bluesky"
        url: "https://bsky.app"
        short_url: "bsky.app"
      - name: "Threads"
        url: "https://threads.net"
        short_url: "threads.net"
      - name: "Mastodon"
        url: "https://mastodon.social"
        short_url: "mastodon.social"
      - name: "Reddit"
        url: "https://reddit.com"
        short_url: "reddit.com"
      - name: "Tumblr"
        url: "https://tumblr.com"
        short_url: "tumblr.com"
      - name: "Twitch"
        url: "https://twitch.tv"
        short_url: "twitch.tv"
      - name: "YouTube"
        url: "https://youtube.com"
        short_url: "youtube.com"
      - name: "Pinterest"
        url: "https://pinterest.com"
        short_url: "pinterest.com"
      - name: "Strava"
        url: "https://strava.com"
        short_url: "strava.com"
      - name: "VSCO"
        url: "https://vsco.co"
        short_url: "vsco.co"
      - name: "DeviantArt"
        url: "https://deviantart.com"
        short_url: "deviantart.com"
      - name: "Wattpad"
        url: "https://wattpad.com"
        short_url: "wattpad.com"
      - name: "Flickr"
        url: "https://flickr.com"
        short_url: "flickr.com"
      - name: "Gravatar"
        url: "https://gravatar.com"
        short_url: "gravatar.com"
      - name: "Bandcamp"
        url: "https://bandcamp.com"
        short_url: "bandcamp.com"
      - name: "TripAdvisor Profiles"
        url: "https://tripadvisor.com/profile"
        short_url: "tripadvisor.com/profile"
      - name: "Yelp"
        url: "https://yelp.com"
        short_url: "yelp.com"
      - name: "Airbnb Profiles"
        url: "https://airbnb.com/users/show"
        short_url: "airbnb.com/users/show"
      - name: "Quora Profiles"
        url: "https://quora.com/profile"
        short_url: "quora.com/profile"
      - name: "Steam Community"
        url: "https://steamcommunity.com/profiles/"
        short_url: "steamcommunity.com/profiles/"
      - name: "Xbox Gamertag"
        url: "https://xboxgamertag.com/search/"
        short_url: "xboxgamertag.com/search/"
      - name: "Chess.com"
        url: "https://chess.com/member"
        short_url: "chess.com/member"
      - name: "osu!"
        url: "https://osu.ppy.sh/users"
        short_url: "osu.ppy.sh/users"